name: Docker Image CI

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        
      - uses: crazy-max/ghaction-docker-meta@v1
        name: Docker meta
        id: docker_meta
        with:
          images: irontony0438/fellow_friend
          tag-semver: |
            { {version} }
            { {major} }.{ {minor} }
      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx
        
      - uses: docker/login-action@v1
        name: Login to DockerHub
        with:
          username: ${ { secrets.DOCKER_USERNAME } }
          password: ${ { secrets.DOCKER_TOKEN } }
      - uses: docker/build-push-action@v2
        name: Build and push
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${ { steps.docker_meta.outputs.tags } }
          labels: ${ { steps.docker_meta.outputs.labels } }